export const WINDOW_DRAG_HEIGHT = 52;
export const CHROME_RAIL_TOP = WINDOW_DRAG_HEIGHT + 10;
export const CHROME_RAIL_LEFT = 14;
export const CHROME_RAIL_BUTTON_SIZE = 29;
export const CHROME_RAIL_GAP = 4;
export const CHROME_RAIL_COLLAPSED_SAFE_INSET =
  CHROME_RAIL_LEFT + (CHROME_RAIL_BUTTON_SIZE * 2) + CHROME_RAIL_GAP + 20;
