export const WINDOW_DRAG_HEIGHT = 52;

const TRAFFIC_LIGHT_LEFT = 16;
const TRAFFIC_LIGHT_GROUP_WIDTH = 56;
const TRAFFIC_LIGHT_GAP = 12;

export const SIDEBAR_TOGGLE_TOP = 16;
export const SIDEBAR_TOGGLE_LEFT = TRAFFIC_LIGHT_LEFT + TRAFFIC_LIGHT_GROUP_WIDTH + TRAFFIC_LIGHT_GAP;
export const SIDEBAR_TOGGLE_SIZE = 24;
